# ~/etc/bash/bash_aliases
# ln .bash_aliases
alias gita="git add *"
alias gitac="git add * && git commit -m update"
alias gitacp="git add * && git commit -m update && git push"
alias gitp="git push"
alias lsa='ls -a'
alias lsl='ls -l'
alias lsla='ls -la'
alias printsc='scrot -F ~/tmp/scrot/%b%d::%H%M%S.png'
