# ~/etc/bash/bash_aliases
# ln .bash_aliases
alias vim="vi"
alias vi="nvim"

alias gita="git add *"
alias gitc="bash ~/etc/shellScripts/gitCommit.sh"
alias gitp="git push"
alias gitac="git add * && git add -u && gitc"
alias gitacp="git add * && git add -u && gitc && git push"

alias lsa='ls -a'
alias lsl='ls -l'
alias lsla='ls -la'

alias printsc='scrot -F ~/img/scrot/%b%d::%H%M%S.png'
